objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipName>students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/mapStudents.cls
public class mapStudents{
public Map<String, Set<ID>> mapStudent()
{
Map<String, Set<ID>> ms = new Map<String, Set<ID>>();
list<class__c> cls = [select name from class__c];
for (class__c clas : cls)
{
set<ID> sid =  new set<ID>();
    list <student__c> st = [select ID from student__c where class__r.name =: clas.name];
    for (student__c stu : st)
    {
        sid.add(stu.ID);

    }
ms.put(clas.name,sid);
}
return ms;
}
}